/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module test_input_8 (
    output reg out,
    input inputA1,
    input inputA2,
    input inputB1,
    input inputB2,
    output reg result
  );
  
  
  
  always @* begin
    result = 1'h0;
    out = 1'h0;
    if (inputA1 == inputA2) begin
      if (inputB1 == inputB2) begin
        result = 1'h1;
      end
    end
  end
endmodule
